In [3]:
import numpy as np
import matplotlib.pyplot as plt

treasures = [
    [24,70,41,21,60],
    [47,82,87,80,35],
    [73,89,100,90,17],
    [77,83,85,79,55],
    [12,27,52,15,30]
]

hunters = [
    [2,4,3,2,4],
    [3,5,5,5,3],
    [4,5,8,7,2],
    [5,5,5,5,4],
    [2,3,4,2,3]
]

treasures = np.array(treasures)
hunters = (np.array(hunters))+10000

print(np.divide(treasures*7000,hunters))

[[16.79664067 48.98040784 28.69139258 14.69706059 41.98320672]
 [32.89013296 57.37131434 60.86956522 55.97201399 24.4926522 ]
 [51.07956817 62.26886557 69.94404476 62.95593085 11.89762048]
 [53.87306347 58.07096452 59.47026487 55.27236382 38.48460616]
 [ 8.39832034 18.8943317  36.38544582 10.49790042 20.99370189]]


In [ ]:
plt.imshow(np.divide(treasures,hunters), cmap = "hot", interpolation = "nearest")
plt.show()